version: 2.1

orbs:
  android: circleci/android@2.0.3

jobs:
  build:
    docker:
      - image: cimg/android:2022.04
    steps:
      - checkout 
      - run: echo "hello world"
  test:
    docker:
      - image: cimg/android:2022.04
      - image: cimg/android:2022.01
      - image: cimg/android:2021.12
      - image: cimg/android:2021.08
    parallelism: 4
    steps:
      - checkout
      - run: echo "begin testing"
      - android/create-avd:
          avd-name: myavd
          install: true
          system-image: system-images;android-29;default;x86
      - android/start-emulator:
          avd-name: myavd
          no-window: true
          restore-gradle-cache-prefix: v1a
      - android/run-tests
      - android/save-gradle-cache:
          cache-prefix: v1a
      # - android/run-ui-tests:
      #     matrix:
      #       parameters:
      #         system-image:
      #           - system-images;android-28;default;x86
      #           - system-images;android-29;default;x86
      #     name: ui-tests-<<matrix.system-image>>


workflows:
  build-workflow:
    jobs:
      - build
      - test:
          requires:
          - build
